// seo.config.ts
export const SEO = {
  siteName: "Real Matka",
  siteUrl: "https://realmatka.in",
  defaultTitle: "Real Matka - Game Rates, Market Results, Charts & Live App",
  defaultDescription:
    "Real Matka provides game rates, live market results, jodi and panna charts, market timings, and secure access to the Real Matka web app.",
  defaultKeywords: [
    "real matka",
    "satta matka",
    "satta matka live",
    "satta matka online",
    "online satta matka",
    "online play satta matka",
    "play satta matka online",
    "online satta matka kaise khele",
    "real matka result",
    "matka result",
    "matka result today",
    "satta matka result",
    "live matka result",
    "open close result",
    "today matka result",
    "kalyan result",
    "main bazar result",
    "rajdhani night result",
    "time bazar result",
    "real matka chart",
    "matka chart",
    "old matka chart",
    "real matka game rate",
    "matka game rates",
    "single digit rate",
    "jodi digit rate",
    "panna rate",
    "single pana rate",
    "double pana rate",
    "triple pana rate",
    "half sangam rate",
    "full sangam rate",
    "jodi chart",
    "matka jodi chart",
    "jodi chart today",
    "daily jodi chart",
    "panna chart",
    "open panna chart",
    "close panna chart",
    "panna chart today",
    "market result",
    "market timing",
    "matka market timing",
    "matka open close",
    "matka app",
    "online matka app",
    "matka app download",
    "satta matka app",
    "satta matka app download",
    "matka apk",
    "matka apk download",
    "real matka apk",
    "ai matka guessing",
    "ai jodi guessing",
    "matka guessing today",
    "final ank guessing",
    "open close guessing",
    "jodi guessing",
    "panna guessing",
  ],
};
